{
 "title": "Kubernetes Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Kuberentes Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU Usage (from Limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container_name, workload_name, namespace) (\n    rate(groundcover_container_m_cpu_usage_seconds_total{}[60s]) / \n    groundcover_container_cpu_limit_m_cpu{}\n)",
     "legendFormat": "{{container_name}}@{{namespace}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (from Limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container_name, workload_name, namespace) (\n    groundcover_container_mem_working_set_bytes{} / \n    groundcover_container_memory_limit_bytes{}\n)",
     "legendFormat": "{{container_name}}@{{namespace}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n    rate(groundcover_node_m_cpu_usage_seconds_total{}[60s]) / \n    groundcover_node_allocatable_cpum_cpu{}\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n    groundcover_node_mem_working_set_bytes{} / \n    groundcover_node_allocatable_mem_bytes{}\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "groundcover_pvc_usage_percent{}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "groundcover_node_disk_space_used_percent{}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Application SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Workload Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (\n    workload_name, namespace\n) (increase(\n    groundcover_workload_error_counter{\n    type=~\".*http|grpc\",status_code!~\"4.*\", role=\"server\"}[60s]\n) ) or (0))\n/\nsum by (\n    workload_name, namespace\n) (increase(\n    groundcover_workload_total_counter{\n    type=~\".*http|grpc\", role=\"server\"}[60s]\n)) ",
     "legendFormat": "{{workload_name}} @ {{namespace}}"
    }
   ]
  },
  {
   "title": "Workload P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    groundcover_workload_latency_seconds{\n        type=~\".*http|grpc\", role=\"server\", quantile=\"0.50\"\n    }\n) by (workload_name, namespace)",
     "legendFormat": "{{workload_name}}@{{namespace}}"
    }
   ]
  },
  {
   "title": "Workload Request Rate Drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(\n    rate(groundcover_workload_total_counter{\n        type=~\".*http|grpc\", role=\"client\"}[60s]\n    )\n) by (workload_name, namespace)",
     "legendFormat": "{{workload_name}}"
    }
   ]
  },
  {
   "title": "Workload P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    groundcover_workload_latency_seconds{\n        type=~\".*http|grpc\", role=\"server\", quantile=\"0.95\"\n    }\n) by (workload_name, namespace)",
     "legendFormat": "{{workload_name}}@{{namespace}}"
    }
   ]
  },
  { "title": "Kubernetes Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Container OOM Kills ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "increase(groundcover_resource_issue_counter{type=\"container_crash\", crash_reason=\"OOMKilled\"})",
     "legendFormat": "{{container_name}}@{{namespace}}"
    }
   ]
  },
  {
   "title": "Deployment Not Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(groundcover_resource_issue_counter{type=\"unavailable_deployment\"})",
     "legendFormat": "{{workload_name}}@{{namespace}}"
    }
   ]
  }
 ]
}